language: cpp
compiler:
  - gcc

dist: xenial

services:
  - docker

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0

script:
  - ./run.py build-fc
  - ./run.py build-gui
  - ./tools/scripts/build_utest.sh
  - ./tools/scripts/run_utest.sh
