language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.10-linux64.tar.xz
  - tar xf arduino-1.6.10-linux64.tar.xz
  - sudo mv arduino-1.6.10 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  - tar zxvf cmake-3.3.2-Linux-x86_64.tar.gz
script:
  - cd FlightController
  - mkdir build
  - cd build
  - ../../cmake-3.3.2-Linux-x86_64/bin/cmake .. -DARDUINO_TOOLCHAIN_FILE=../cmake/ArduinoToolchain.cmake -DARDUINO_1_5=ON
  - make
