language: cpp
compiler:
    - gcc

sudo: required
dist: trusty

services:
  - docker

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - docker pull carlosgalvezp/quadcopter
script:
  - docker run carlosgalvezp/quadcopter /bin/bash ./tools/scripts/build_fc.sh
  - ./tools/scripts/build_utest.sh
  - ./tools/scripts/run_utest.sh
