#ifndef TELEMETRY_PROTOCOL_H
#define TELEMETRY_PROTOCOL_H

#define TELEMETRY_MAGIC_WORD				"$F"

// ** COMMANDS **
#define TELEMETRY_CMD_OUT_STATUS			1

#define TELEMETRY_CMD_OUT_IMU				100
#define TELEMETRY_CMD_OUT_MAG				101
#define TELEMETRY_CMD_OUT_BARO				102
#define TELEMETRY_CMD_OUT_TEMP				103
#define TELEMETRY_CMD_OUT_RC				104
#define TELEMETRY_CMD_OUT_BATTERY			105
#define TELEMETRY_CMD_OUT_GPS				106
#define TELEMETRY_CMD_OUT_SONAR				107

#define TELEMETRY_CMD_OUT_ATTITUDE			150
#define TELEMETRY_CMD_OUT_CONTROL			151
#define TELEMETRY_CMD_OUT_CONFIG			152

#define TELEMETRY_CMD_IN_CONFIG				200

#define TELEMETRY_ACK						250
#define TELEMETRY_NACK						251

#endif